development:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: 2smmo523ab
  host: localhost
  port: 5432

test:
  adapter: postgresql
  encoding: utf8
  database: postgres
  pool: 5
  username: postgres
  password: 2smmo523ab
  host: localhost
  port: 5432

production:
  adapter: postgresql
  encoding: utf8
  database: postgres
  username: postgres
  password: 2smmo523ab
  port: 5432
